# -*- coding: utf-8 -*-
"""TONIoT.input

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnzIx-fg7OvbiH1YgCvnlDEJKWwrx8Tg

# **head**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
path = "/content/drive/MyDrive/train_test_network.csv"

print(path)

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(path)

# Now you can access the attributes on the DataFrame
print(df.head())

"""# **shape**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
path = "/content/drive/MyDrive/train_test_network.csv"

print(path)

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(path)

# Now you can access the attributes on the DataFrame

print(df.shape)

"""# **columns**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
path = "/content/drive/MyDrive/train_test_network.csv"

print(path)

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(path)

# Now you can access the attributes on the DataFrame

print(df.columns)

"""# **info**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
path = "/content/drive/MyDrive/train_test_network.csv"

print(path)

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(path)

# Now you can access the attributes on the DataFrame

print(df.info())

"""# size

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Path to your dataset
path = "/content/drive/MyDrive/train_test_network.csv"
print("Dataset Path:", path)

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(path)

# Display first 5 rows
print("\n📄 First 5 Rows of Dataset:")
print(df.head())

# -----------------------------
# ✅ Find size of dataset
# -----------------------------
print("\n📊 Dataset Size Information:")
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("Total Cells (Rows × Columns):", df.size)

"""# null values"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Path to your dataset
path = "/content/drive/MyDrive/train_test_network.csv"
print("Dataset Path:", path)

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(path)

# Display first 5 rows
print("\n📄 First 5 Rows of Dataset:")
print(df.head())

# -----------------------------
# ✅ Dataset Size
# -----------------------------
print("\n📊 Dataset Size Information:")
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("Total Cells (Rows × Columns):", df.size)

# -----------------------------
# ✅ Null / Missing Values
# -----------------------------
print("\n❗ Checking for Null (Missing) Values:")
null_values = df.isnull().sum()
print(null_values)

"""# duplicate values"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Path to your dataset
path = "/content/drive/MyDrive/train_test_network.csv"
print("📂 Dataset Path:", path)

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(path)

# Display first 5 rows
print("\n📄 First 5 Rows of Dataset:")
print(df.head())

# -----------------------------
# ✅ Dataset Size
# -----------------------------
print("\n📊 Dataset Size Information:")
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("Total Cells (Rows × Columns):", df.size)

# -----------------------------
# ✅ Null / Missing Values
# -----------------------------
print("\n❗ Checking for Null (Missing) Values:")
null_values = df.isnull().sum()
print(null_values)

# Total number of missing values
total_nulls = null_values.sum()
print("\n🔢 Total Missing Values in Entire Dataset:", total_nulls)

# Columns with missing values only
print("\n📋 Columns with Missing Values:")
print(null_values[null_values > 0])

# -----------------------------
# ✅ Duplicate Values
# -----------------------------
print("\n📑 Checking for Duplicate Rows:")
duplicate_count = df.duplicated().sum()
print("Total Duplicate Rows:", duplicate_count)

# Optional: show sample duplicate rows if they exist
if duplicate_count > 0:
    print("\n🔍 Sample Duplicate Rows:")
    print(df[df.duplicated()].head())

# -----------------------------
# ✅ Optional: Visualize Missing Data
# -----------------------------
plt.figure(figsize=(10, 5))
null_values.plot(kind='bar', color='skyblue')
plt.title('Missing Values per Column')
plt.xlabel('Columns')
plt.ylabel('Number of Missing Values')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# Features"""

import pandas as pd

# Path to your dataset
path = "/content/drive/MyDrive/train_test_network.csv"

# Read the CSV file
df = pd.read_csv(path)

# -----------------------------
# ✅ Find and Display Features
# -----------------------------
print("🧩 DATASET FEATURES\n")

# 1️⃣ List all feature (column) names
print("📋 Feature Names:")
for col in df.columns:
    print("-", col)

# 2️⃣ Number of total features (columns)
print("\n🔢 Total Number of Features:", len(df.columns))

# 3️⃣ Show data type of each feature
print("\n📘 Data Type of Each Feature:")
print(df.dtypes)

# 4️⃣ Count of unique values per feature
print("\n🔠 Unique Value Count per Feature:")
print(df.nunique())

# 5️⃣ Summary of numeric features
print("\n📈 Summary of Numeric Features:")
print(df.describe())

# 6️⃣ Summary of categorical features
print("\n🔤 Summary of Categorical Features:")
print(df.describe(include=['object']))

"""# line chart

"""

# -------------------------------------------------------
# 📈 Auto Line Chart for Any Dataset
# -------------------------------------------------------
import pandas as pd
import matplotlib.pyplot as plt

# 1️⃣ Load the dataset
path = "/content/drive/MyDrive/train_test_network.csv"
df = pd.read_csv(path)

# 2️⃣ Display dataset info
print("📄 First 5 Rows of Dataset:")
print(df.head())
print("\n📊 Dataset Columns:")
print(df.columns.tolist())

# 3️⃣ Automatically detect numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print("\n🔢 Numeric Columns Detected:")
print(numeric_cols)

# 4️⃣ Check if at least two numeric columns exist
if len(numeric_cols) >= 2:
    x_column = numeric_cols[0]
    y_column = numeric_cols[1]

    print(f"\n✅ Plotting Line Chart: '{y_column}' vs '{x_column}'")

    # 5️⃣ Sample smaller portion if dataset is large
    df_sample = df[[x_column, y_column]].dropna().sample(n=1000, random_state=1)

    # 6️⃣ Plot the line chart
    plt.figure(figsize=(10,5))
    plt.plot(df_sample[x_column], df_sample[y_column], color='blue', linewidth=1.5)
    plt.title(f"Line Chart of '{y_column}' vs '{x_column}'", fontsize=14)
    plt.xlabel(x_column, fontsize=12)
    plt.ylabel(y_column, fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.show()
else:
    print("⚠️ Not enough numeric columns found to create a line chart.")